# Generated by Django 3.0.5 on 2020-04-23 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200422_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
