# Generated by Django 3.0.5 on 2020-04-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_taskuser_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskuser',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
