# Generated by Django 3.0.5 on 2020-04-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200423_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
