# Generated by Django 3.0.5 on 2020-04-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200424_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('IP', 'In progress'), ('DN', 'Done')], default='OP', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TaskUser')),
            ],
        ),
    ]
