# Generated by Django 3.0.5 on 2020-04-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_archivedtodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedtodo',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
