# Generated by Django 3.0.5 on 2020-04-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200428_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200, null=True, unique=True),
        ),
    ]
