# Generated by Django 3.0.5 on 2020-04-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_vistors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vistors',
            new_name='Visitors',
        ),
    ]
