# Generated by Django 3.0.5 on 2020-04-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_visitors_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='title',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
